spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pdfreaderdb
    username: pdf_reader_user
    password: pdf_reader_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reader-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.pdf_reader_ms.model.kafka.consumer.RequestDto
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

client:
  filenet:
    url: http://localhost:8081
    path: v1/pdfs/
  asan:
    url: http://localhost:8081
    path: v1/personals/
  pdf-analyzer:
    url: http://localhost:8081
    path: v1/analysis/
